[package]
name = "throttle"
edition = "2021"
version = "0.1.0"

[dependencies]
eframe = "0.28.1"
nvml-wrapper = "0.10.0"
rdev = "0.5.3"
sysinfo = "0.30.12"

[profile.release]
opt-level = 3
debug = false
lto = true
codegen-units = 1
panic = "abort"
strip = true
